In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
tensor = torch.tensor([[[3,5,5],[2,1,2]],[[2,1,2],[3,2,5]],[[1,2,5],[5,1,2]]])
tensor

tensor([[[3, 5, 5],
         [2, 1, 2]],

        [[2, 1, 2],
         [3, 2, 5]],

        [[1, 2, 5],
         [5, 1, 2]]])

In [9]:
tensor.ndim

3

In [10]:
tensor.shape

torch.Size([3, 2, 3])

In [11]:
for i in range(3):
  print(tensor[i])

tensor([[3, 5, 5],
        [2, 1, 2]])
tensor([[2, 1, 2],
        [3, 2, 5]])
tensor([[1, 2, 5],
        [5, 1, 2]])


### Random Tensor

In [12]:
# Create a random tensor
random_tensor = torch.rand(1,4,10)
random_tensor

tensor([[[0.2252, 0.8289, 0.5424, 0.3759, 0.6442, 0.0365, 0.5463, 0.7920,
          0.7327, 0.6186],
         [0.7600, 0.3225, 0.1366, 0.1011, 0.9143, 0.8982, 0.1030, 0.0967,
          0.6555, 0.6662],
         [0.4503, 0.5014, 0.3150, 0.3685, 0.3091, 0.1315, 0.7503, 0.4610,
          0.4115, 0.5208],
         [0.4280, 0.6321, 0.3081, 0.1921, 0.7942, 0.4723, 0.2551, 0.2430,
          0.3746, 0.7398]]])

In [13]:
random_tensor.ndim

3

In [14]:
random_tensor.shape

torch.Size([1, 4, 10])

In [15]:
random_image_size_tensor = torch.rand(224,224,3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [16]:
# create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
zero.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [19]:
# Use torch.arange
one_to_ten = torch.arange(start=1,end=11)

In [20]:
# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
Three big error are
1. Tensor are not right datatype
2. Tensor are not shape
3. Not right device

In [21]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32,
                               device="cpu",
                               requires_grad=True)
float_32_tensor.dtype, float_32_tensor

(torch.float32, tensor([3., 6., 9.], requires_grad=True))

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.size(0), float_16_tensor.shape[0]

(3, 3)

In [23]:
(float_16_tensor * float_32_tensor).type(torch.float64).dtype

torch.float64

 ### tensor operations
 Tensor operation includes
 * Addition
 * Subtraction
 * Multiplication
 * Division
 * Matrix Mul

In [24]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [25]:
(tensor * 10).dtype

torch.int64

In [26]:
(tensor / 2).dtype

torch.float32

### Multrix multiplicatio
two main ways of performing multiplication in neural network and deep learning
1. Element-wise mul
2. matrix mul (dot product)

In [27]:
tensor * tensor # element wise mul

tensor([1, 4, 9])

In [28]:
torch.matmul(tensor, tensor) # dot product
tensor @ tensor

tensor(14)

### shape errors when matmul
1. inner dim must match
* (3,2) @ (3,2) won't work
* (2,3) @ (3,2) will work
* (4,2) @ (2,5) will work
2. The result mat has the shape of outer dim
* (4,2) @ (2,5) = (4,5)

In [29]:
(torch.rand(4,2) @ torch.rand(2,5)).shape

torch.Size([4, 5])

In [30]:
# shape for mat mul
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

to fix our tensor shape issues we can manipulate of shape of one tensor using transpose


In [31]:
print(torch.mm(tensor_A, tensor_B.T))
print(torch.mm(tensor_A.T, tensor_B))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 76, 103],
        [100, 136]])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [32]:
# Create a tensor
x = torch.arange(0,100,10).type(torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [33]:
x.min(), x.max(), x.mean(), x.sum()

(tensor(0.), tensor(90.), tensor(45.), tensor(450.))

In [34]:
x[torch.argmin(x)]

tensor(0.)

## Reshaping, stacking, squeezing, unsqueezing tensors
* Reshaping - reshpae the input tensor to defined shape
* View -  return a view of input tensor of certain shape but keep the smae memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* unsqueeze - add a '1' dimension to a target tensor
* permute - return a view of the input with dimensions permuted (swapper) in a certain way

In [35]:
x = torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [36]:
x.reshape(4,3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [37]:
z = x.view(4,3)

In [38]:
z[:,0:1] = 1
z,x

(tensor([[ 1.,  2.,  3.],
         [ 1.,  5.,  6.],
         [ 1.,  8.,  9.],
         [ 1., 11., 12.]]),
 tensor([ 1.,  2.,  3.,  1.,  5.,  6.,  1.,  8.,  9.,  1., 11., 12.]))

In [39]:
z_stacked = torch.stack([z,z,z], dim=2)
z_stacked,z_stacked.shape

(tensor([[[ 1.,  1.,  1.],
          [ 2.,  2.,  2.],
          [ 3.,  3.,  3.]],
 
         [[ 1.,  1.,  1.],
          [ 5.,  5.,  5.],
          [ 6.,  6.,  6.]],
 
         [[ 1.,  1.,  1.],
          [ 8.,  8.,  8.],
          [ 9.,  9.,  9.]],
 
         [[ 1.,  1.,  1.],
          [11., 11., 11.],
          [12., 12., 12.]]]),
 torch.Size([4, 3, 3]))

In [46]:
x_reshaped = x.reshape(1,12)
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_reshaped.shape, x_squeezed, x_squeezed.shape

(tensor([[ 1.,  2.,  3.,  1.,  5.,  6.,  1.,  8.,  9.,  1., 11., 12.]]),
 torch.Size([1, 12]),
 tensor([ 1.,  2.,  3.,  1.,  5.,  6.,  1.,  8.,  9.,  1., 11., 12.]),
 torch.Size([12]))

In [55]:
print(f"Prev target: {x_squeezed}")
print(f"Prev shape: {x_squeezed.size()}")

x_unsqueezed = x_squeezed.unsqueeze(dim=1).unsqueeze(1).unsqueeze(0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New shape: {x_unsqueezed.squeeze()}")

Prev target: tensor([ 1.,  2.,  3.,  1.,  5.,  6.,  1.,  8.,  9.,  1., 11., 12.])
Prev shape: torch.Size([12])

New tensor: tensor([[[[ 1.]],

         [[ 2.]],

         [[ 3.]],

         [[ 1.]],

         [[ 5.]],

         [[ 6.]],

         [[ 1.]],

         [[ 8.]],

         [[ 9.]],

         [[ 1.]],

         [[11.]],

         [[12.]]]])
New shape: torch.Size([1, 12, 1, 1])
New shape: tensor([ 1.,  2.,  3.,  1.,  5.,  6.,  1.,  8.,  9.,  1., 11., 12.])


In [64]:
# torch.permute = rearange the shape and order of the tensor
# permute is the view of orignal, meaning changes in permuted would change x_orignal

x_original = torch.rand(size=(224,224,3))
x_permuted = torch.rand(x_original.permute(2,0,1).shape)
x_original.shape, x_permuted.shape
x_permuted[0,0,0] = 1
x_original[0,0,0], x_permuted[0,0,0]


(tensor(0.8145), tensor(1.))

### Indexing (selecting data from tensors)

In [87]:
# Create a tensor
import torch
x = torch.arange(1,17).reshape(4,2,2)
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])

In [89]:
x[0,1,1]

tensor(4)

In [98]:
# semi colon to find all of the dim
x[0:3:2]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 9, 10],
         [11, 12]]])

In [100]:
x[:,1,:]

tensor([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])

## pytorch tensors and numpy
* data in numpy, want in pytorch tensor -> `torch.from_nmpy(ndarray)`
* pytorch tensor -> numpy -> `torch.Tensor.numpy()`

In [103]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
back_to_np = tensor.numpy()
array, tensor,back_to_np
# they dont share memory like permute and view does

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

## Reproducbility (trying to take random out of random)
`start with random -> tensor operation -> update random num -> loop`
reduce the randomness in nn and pytorch comes the concept of random seed.
essentially what the random seed does is flavour the randomness
lets make random but reproducable

In [131]:
import torch

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,6)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,6)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B == random_tensor_A)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000]])
tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True]])


## Running tensors on GPUS

### 1. Getting a GPU
1. Use google colab for free GPU
2. get your own getoutput
3. Use cloud computing and rent GPU

In [39]:
!nvidia-smi

Tue Nov  4 10:23:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   77C    P0             36W /   70W |     150MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [40]:
import torch
torch.cuda.is_available()

True

In [41]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device, torch.cuda.device_count()

('cuda', 1)

## 3. putting tensor and models in GPU
the reason we want out tensors and model iin gpu is for faasster computation

In [42]:
tensor = torch.tensor([1,2,3]) # by default on CPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [43]:
# Move tensor to GPU (if avavilable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. moving tensors back to cpu

In [44]:
# tensor is on GPU cant transform it to numpy
# copy to cpu then to numpy since numpy cannot run tensor ops on GPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [45]:
torch.manual_seed(0)
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [46]:
torch.manual_seed(0)
another_random_tensor = torch.rand(1,7)
another_random_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [47]:
torch.matmul(random_tensor, another_random_tensor.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [48]:
torch.cuda.manual_seed(1234)
gpu_random = torch.rand(2,3,device=device)
torch.cuda.manual_seed(1234)
gpu_random1 = torch.rand(2,3,device=device)
answer = gpu_random @ gpu_random1.T
answer, answer.min(), answer.max(), answer.argmin(), answer.argmax()


(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 tensor(0.8358, device='cuda:0'),
 tensor(1.4578, device='cuda:0'),
 tensor(1, device='cuda:0'),
 tensor(3, device='cuda:0'))

In [49]:
torch.cuda.manual_seed(7)
random_tensor = torch.rand(1,1,1,10, device=device)
squeezed_tensor = random_tensor.squeeze()
print(f"First tensor: {random_tensor}, tensor_shape: {random_tensor.shape}")
print(f"queezed tensor: {squeezed_tensor}, tensor_shape: {squeezed_tensor.shape}")

First tensor: tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0'), tensor_shape: torch.Size([1, 1, 1, 10])
queezed tensor: tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0'), tensor_shape: torch.Size([10])
